[theme]
base="light"
primaryColor="#348e03"  # Green color for primary buttons and highlights
backgroundColor="#f8f8fb"  # Very light background for a clean look
secondaryBackgroundColor="#dae9fd"  # A softer blue for secondary elements
textColor="#2c3e50"  # Dark gray text for clear readability

# Optional, for enhanced UI appearance:
font="sans serif"  # A modern font, easy on the eyes for a game-like interface
codeColor="#333333"  # Dark color for any code or terminal elements, to contrast against light background

[layout]
wideMode=true  # Make the layout wider, ideal for game environments

[sidebar]
backgroundColor="#ecf1f4"  # Light gray sidebar background for contrast
textColor="#2c3e50"  # Dark text color for readability
