[theme]
base="light"
primaryColor="#FF6F61"  # Neon Pink
backgroundColor="#1e1e2f"  # Dark greyish-blue background
secondaryBackgroundColor="#2a2a3a"  # Slightly lighter greyish-blue for contrast
textColor="#F8F8F8"  # Light text for good contrast

# Accent colors
secondaryColor="#FFEB3B"  # Neon Yellow
tertiaryColor="#4CAF50"  # Neon Green
quaternaryColor="#FF9800"  # Neon Orange
highlightColor="#E91E63"  # Strong Neon Pink for highlights and buttons

# Interactive element colors
buttonColor="#FF9800"  # Neon Orange button color
buttonHoverColor="#FF5722"  # Hover effect for buttons with a deeper orange
